CREATE TABLE STOP (
ID_STOP INT AUTO_INCREMENT PRIMARY KEY,
ID_ROUTE INT  NOT NULL,
DESCRIPTION VARCHAR(250) NOT NULL,
LATITUDE DOUBLE NOT NULL,
LONGITUDE DOUBLE NOT NULL,
STATUS VARCHAR(50) NOT NULL,
DELIVERY_RADIUS INT NOT NULL,
foreign key(ID_ROUTE) references ROUTE(ID_ROUTE)
);